server:
  port: 9001

spring:
  application:
    name: Library
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true